app = 'game-of-life'
primary_region = 'ewr'

[build]

[env]
  HOST = '0.0.0.0'
  PORT = '8080'
  DB_PATH = '/data/db/game-of-life.db'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "persist"
  destination = "/data/db"
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
